[camera]
mouse_sensitivity_x = 8e-4
mouse_sensitivity_y = 5e-4

[camera.fixed_angle]
min_distance = 5.0
max_distance = 20.0
zoom_speed = 0.7
rotation_smoothing = 45.0
translation_smoothing = 50.0

[camera.first_person]
translation_smoothing = 0.3
rotation_smoothing = 0.3
min_degrees_looking_down = 36.0
min_degrees_looking_up = 50.0
tracking_smoothing = 0.1

[camera.third_person]
translation_smoothing = 0.3
rotation_smoothing = 0.3
tracking_smoothing = 0.1
min_degrees_looking_down = 36.0
min_degrees_looking_up = 50.0
min_distance = 0.01
max_distance = 10.0
zoom_speed = 0.7
min_distance_to_objects = 1e-1
zoom_in_smoothing = 0.3
zoom_out_smoothing = 1.2
