[package]
authors = ["Jan Hohenheim <jan@hohenheim.ch>"]
edition = "2021"
name = "foxtrot"
publish = false
version = "0.1.7"
license = "MIT or Apache-2.0"
exclude = ["dist", "build", "assets", "credits", "saves", "resources"]

[features]
default = [
    "core",
    "native-dev",
    "dev",
    "native",
]

core = [
    "bevy/bevy_winit",
    "bevy/render",
    "bevy/hdr",
    "bevy/png",
    "bevy/jpeg",
    "bevy/bevy_asset",
    "bevy/x11",
    "bevy/animation",
    "bevy/serialize",
]

dev = [
    "dep:bevy_editor_pls",
    "dep:bevy_prototype_debug_lines",
]

native-dev = [
    "bevy/dynamic",
    "bevy/filesystem_watcher",
]

native = [
    "bevy_rapier3d/parallel",
    "bevy_rapier3d/simd-nightly",
    "bevy_hanabi",
]

wasm = [
    "bevy_rapier3d/wasm-bindgen"
]

[dependencies]
bevy = { version = "^0.9.1", default-features = false }
bevy_kira_audio = "0.13"
bevy_asset_loader = { git = "https://github.com/NiklasEi/bevy_asset_loader.git", rev = "9a7966c9e7a44026a2192292390b315d28c88ca7", features = ["progress_tracking"] }
bevy_common_assets = { version = "0.4.0", features = ["ron", "toml"] }
bevy_egui = "0.19"
serde = { version = "1", features = ["derive"] }
indexmap = { version = "1", features = ["serde-1"] }
strum = "0.24.1"
strum_macros = "0.24.3"
ron = "0.8.0"
regex = "1"
chrono = "0.4.23"
glob = "0.3.1"
oxidized_navigation = "0.2.0"
bitflags = "1.3.2"
iyes_progress = "0.7.1"
unicode-segmentation = "1.10.1"
bevy_hanabi = { version = "0.5", optional = true }
anyhow = "1.0.69"
bevy_rapier3d = { version = "0.20.0", features = ["serde-serialize"] }

# keep the following in sync with Bevy's dependencies
winit = { version = "0.27", default-features = false }
image = { version = "0.24", default-features = false }

[dependencies.bevy_prototype_debug_lines]
version = "0.9.0"
optional = true
features = ["3d"]

[dependencies.bevy_editor_pls]
git = "https://github.com/jakobhellermann/bevy_editor_pls"
rev = "6062b860aea87034081399369fd7ef5715f13256"
optional = true

[patch.crates-io.bevy_rapier3d]
git = "https://github.com/janhohenheim/bevy_rapier"
branch = "own-fork"


[build-dependencies]
embed-resource = "1.4"
